server:
  port: 8090
spring:
  application:
    name: gability
  cloud:
    nacos:
      discovery:
        username: nacos # nacos 登录用户名
        password: nacos # nacos 密码
        server-addr: 81.70.142.244:8848 # nacos 服务端地址